### ISSUE TITLE
the cross dataset - dmos.txt in CSIQ

### ISSUE THREAD

**Issue by niebieska** [HuiZeng/BIQA_Toolbox#3]
Hello !
I trained CNN model with TID2013 database and I have a problem in testing with dmos.txt file for CSIQ. The original CSIQ database files contains only xlsx for dmos data. I try make file myself with diffrent combinations  but I do not know what it should contains and the result is always matlab error (for example different number of rows in corr)

Could you help me ?

Thank you very much!!!

**Comment by HuiZeng** [comment]
Hi，I checked my source code and found that I have one dmos.txt file of the CSIQ, and this file was created in 2010. Since about two years have pasted, I cannot remember where I got this .txt file，possibly from some other prior researchers, but it should work with the provided getImdbCSIQ.m in setupDataset. I have uploaded it to my googleDrive: https://drive.google.com/file/d/1Fb29TFNur8TbzQ5N_9f40rWGIQ0LoH62/view?usp=sharing
Hope this can help you.
